---

- hosts: localhost
  vars:
    choosen_hostname: wodka
    github_repo_list:
      https://github.com/MorzeBaltyk/workstation_setup.git: "~/git/workstation_setup"
      https://github.com/MorzeBaltyk/katops.git: "~/git/katops"
    git_user_name: "MorzeBaltyk"
    git_user_email: "chrisdelart@hotmail.fr"

  pre_tasks:
  - name: setup some expected dirs
    file:
      dest: "{{ item }}"
      state: directory
    loop:
    - "~/.privIncludes/"
    - "~/git/"
    tags:
    - git
    - bash

  - name: setup all my github repo
    git:
      repo: {{ item.key }}
      dest: {{ item.value }}
      update: no # We just need to make sure it's there
    with_dict: "{{ github_repo_list }}"
    tags: git

  - name: setup Github account
    shell: |
      git config --global user.name {{ git_user_name }}
      git config --global user.email {{ git_user_email }}
    tags: git

  tasks:
  - name: Setup hostname and needed files
    include: ~/git/workstation_setup/ans/playbooks/localhost.yml

  - name: Install Repo
    include: ~/git/workstation_setup/ans/playbooks/repo.yml

  - name: Install Packages
    include: ~/git/workstation_setup/ans/playbooks/package.yml

  - name: Provision Files
    include: ~/git/workstation_setup/ans/playbooks/replace.yml

  - name: Symlink
    include: ~/git/workstation_setup/ans/playbooks/symlink.yml

  # Need to Source .bash_profile at the end
