---

- hosts: localhost

  pre_tasks:
  - name: setup some expected dirs
    file:
      dest: "{{ item }}"
      state: directory
    loop:
    - "~/.privIncludes/"
    - "~/git/"
    tags:
    - git
    - bash

  - name: setup my workstation setup repo
    git:
      repo: https://github.com/MorzeBaltyk/workstation_setup.git
      dest: ~/git/workstation_setup
      update: no # We just need to make sure it's there
    tags: git

  - name: setup Katops repo
    git:
      repo: https://github.com/MorzeBaltyk/katops.git
      dest: ~/git/katops
      update: no # We just need to make sure it's there
    tags: git

  - name: setup Github account
      command:
        argv:
         - git config --global user.name "MorzeBaltyk"
         - git config --global user.email "chrisdelart@hotmail.fr"
    tags: git

  tasks:
  - name: Setup hostname and needed files
    include: ~/git/workstation_setup/ans/playbooks/localhost.yml

  - name: Install Repo
    include: ~/git/workstation_setup/ans/playbooks/repo.yml

  - name: Install Packages
    include: ~/git/workstation_setup/ans/playbooks/package.yml

  - name: Provision Files
    include: ~/git/workstation_setup/ans/playbooks/replace.yml

  - name: Symlink
    include: ~/git/workstation_setup/ans/playbooks/symlink.yml

  # Need to Source .bash_profile at the end
