---

- hosts: localhost

  tasks:

  - name: Install ansible from github
    git:
      repo: https://github.com/ansible/ansible.git
      dest: ~/ansible

  - name: Install dev ansible
    pip:
      requirements: /home/db0/ansible/requirements.txt
  
  - name: setup bash environment
    lineinfile:
      path: ~/.bashrc
      line: '{{ item }}'
    loop:
    - source ./ansible/hacking/env-setup -q

  - name: create python -> python3 symlink
    file:
      src: /usr/bin/python3
      dest: /usr/bin/python
      state: link
    become: true
 
  - name: Remove standard ansible now that we have devel
    dnf:
      name: ansible
      state: absent
    become: true

  - name: Install other useful packages
    dnf:
      name: '{{ item }}'
      state: latest
    loop:
    - bat
    - exa
    - htop
    - ack
    - task
    become: true

  - name: setup my workstation setup repo
    git:
      repo: https://github.com/db0/workstation_setup.git
      dest: ~/git/workstation_setup
