---

  - hostname:
    name: wodka

  - name: setup some expected dirs
    file:
      dest: "{{ item }}"
      state: directory
    loop:
    - "~/.privIncludes/"
    - "~/git/"
    tags:
    - git
    - bash

  - name: Validate and create if doesn't exist
    stat : path=~/.hushlogin
    register: validate
    tags: hush

  - file:
      path: ~/.hushlogin
      state: '{{ "file" if validate.stat.exists else "touch" }}'
    tags: hush
