---

  - name: set hostname of the workstation
    hostname:
      name: "{{ choosen_hostname }}"
    become: true
    tags: local

  - name: Set timezone to Europe/Amsterdam
    timezone:
      name: Europe/Amsterdam
    become: true
    tags: local

  - name: Set keyboard
    shell: |
      localectl set-locale LANG=en_US.utf8
      localectl set-keymap us
    become: true
    tags: local

  - name: create file to setup proxy
    lineinfile:
        path: ~/.privIncludes/setproxy.notyet
        line: "{{ item }}"
        create: true
    loop:
    - "# Complete later, those values below."
    - "# This Directory is not handle by git."
    - "# Rename file in setproxy.bash, then source .bash_profile "
    - "export proxy_username="
    - "export proxy_password="
    - "export proxy_server="
    - "export proxy_port="
    tags: proxy

#  - name: Validate and create if doesn't exist
#    stat : path=~/.hushlogin
#    register: validate
#    tags: hush

#  - file:
#      path: ~/.hushlogin
#      state: '{{ "file" if validate.stat.exists else "touch" }}'
#      when: ansible_facts['ansible_bios_version'] != "VirtualBox"
#    tags: hush
