---

  - name: create python -> python3 symlink
    file:
      src: /usr/bin/python3
      dest: /usr/bin/python
      state: link
    become: true
    ignore_errors: true
    #when: ansible_distribution == "Fedora"
    tags: os
    
  - name: setup .bash_profile
    file:
      src: ~/git/workstation_setup/.bash_profile
      dest: ~/.bash_profile
      state: link
      force: true
    tags: bash

  - name: setup .bashIncludes
    file:
      src: ~/git/workstation_setup/bashIncludes
      dest: ~/.bashIncludes
      state: link
    tags: bash

  - name: setup .bashrc
    file:
      src: ~/git/workstation_setup/.bashrc
      dest: ~/.bashrc
      state: link
    tags: bash

  - name: setup .screenrc
    file:
      src: ~/git/workstation_setup/.screenrc
      dest: ~/.screenrc
      state: link
    tags: screen

  - name: create .screenrc logs directory
    file:
      dest: ~/.Screenlogs
      state: directory
    tags: screen

